// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3RqH3oOkQD-0fQN3eCEqj_hmHSL-wvwY',
    appId: '1:1021004998637:web:5c7991202dad4717e469e4',
    messagingSenderId: '1021004998637',
    projectId: 'otolink-3af12',
    authDomain: 'otolink-3af12.firebaseapp.com',
    storageBucket: 'otolink-3af12.firebasestorage.app',
    measurementId: 'G-VWF65ZH63L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwGy_ueMHPPVFaeri1rL-wirz-OO-6T_U',
    appId: '1:1021004998637:android:71b6bb822ebc1e15e469e4',
    messagingSenderId: '1021004998637',
    projectId: 'otolink-3af12',
    storageBucket: 'otolink-3af12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjaIMHwFQZi1CqYuYjmSUWe245Kf6Js7c',
    appId: '1:1021004998637:ios:73a234c0e9c5e1f2e469e4',
    messagingSenderId: '1021004998637',
    projectId: 'otolink-3af12',
    storageBucket: 'otolink-3af12.firebasestorage.app',
    iosBundleId: 'com.example.otolink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjaIMHwFQZi1CqYuYjmSUWe245Kf6Js7c',
    appId: '1:1021004998637:ios:73a234c0e9c5e1f2e469e4',
    messagingSenderId: '1021004998637',
    projectId: 'otolink-3af12',
    storageBucket: 'otolink-3af12.firebasestorage.app',
    iosBundleId: 'com.example.otolink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3RqH3oOkQD-0fQN3eCEqj_hmHSL-wvwY',
    appId: '1:1021004998637:web:7232751118c1aea2e469e4',
    messagingSenderId: '1021004998637',
    projectId: 'otolink-3af12',
    authDomain: 'otolink-3af12.firebaseapp.com',
    storageBucket: 'otolink-3af12.firebasestorage.app',
    measurementId: 'G-SPZMGPHTHJ',
  );

}