// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGSsQvManFvqhiMjYzk6he35pFr9fF3yE',
    appId: '1:307129817228:web:36cbb6b2670b4a13c843a9',
    messagingSenderId: '307129817228',
    projectId: 'otolink-38c70',
    authDomain: 'otolink-38c70.firebaseapp.com',
    storageBucket: 'otolink-38c70.firebasestorage.app',
    measurementId: 'G-8GMEG6DSEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPHjGWssOsQ0zUpzoN_d94gCQctA7Azd4',
    appId: '1:307129817228:android:2cf0bdb7b84b5edec843a9',
    messagingSenderId: '307129817228',
    projectId: 'otolink-38c70',
    storageBucket: 'otolink-38c70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNf8ZjBwZE8dxyMzNXu_XH4hqMkEoHMt4',
    appId: '1:307129817228:ios:27e6787a346613ccc843a9',
    messagingSenderId: '307129817228',
    projectId: 'otolink-38c70',
    storageBucket: 'otolink-38c70.firebasestorage.app',
    iosBundleId: 'com.example.otolink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNf8ZjBwZE8dxyMzNXu_XH4hqMkEoHMt4',
    appId: '1:307129817228:ios:27e6787a346613ccc843a9',
    messagingSenderId: '307129817228',
    projectId: 'otolink-38c70',
    storageBucket: 'otolink-38c70.firebasestorage.app',
    iosBundleId: 'com.example.otolink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGSsQvManFvqhiMjYzk6he35pFr9fF3yE',
    appId: '1:307129817228:web:08c8c503a265a6fdc843a9',
    messagingSenderId: '307129817228',
    projectId: 'otolink-38c70',
    authDomain: 'otolink-38c70.firebaseapp.com',
    storageBucket: 'otolink-38c70.firebasestorage.app',
    measurementId: 'G-8PE2PTQ8LF',
  );

}